name: CI - Quality Gates

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Verify dependencies
        run: mvn dependency:go-offline

      - name: Build and verify
        run: mvn verify

  quality-gate:
    name: Quality Gate
    runs-on: ubuntu-latest
    needs: quality-checks
    if: always()

    steps:
      - name: Check quality gate status
        run: |
          if [ "${{ needs.quality-checks.result }}" != "success" ]; then
            echo "❌ Quality checks failed - blocking merge"
            exit 1
          else
            echo "✅ Quality checks passed"
          fi
